name: Build on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify code compiles
        run: python -m compileall .

      - name: Run minimal GUI test
        run: |
          python -c "import sys; \
          from PyQt5.QtWidgets import QApplication; \
          from PyQt5.QtCore import QTimer; \
          from crops_lips import Application; \
          app = QApplication([]); \
          window = Application(); \
          window.show(); \
          QTimer.singleShot(3000, app.quit); \
          sys.exit(app.exec_())"
